//Hotel,Shopping-Mall,Hospital etc Vehicles Parking System
 
 #include<stdio.h>
 
 char a;
 int tnocy=0,tnob=0,tnoc=0,tnoa=0,tnobu=0,tnoov=0,amount=0,count=0;
 //tnoc=total no of cycles
 //tnob=total no of buses
 //tnoov=total no of other vehicles
 

 
	int Cycle()
		{
		 	count++;
		 	tnocy++;
		 	amount=amount+10;	
		 	printf("\nYour Cycle entry are Sucessfully done.\n");
		}
	 
	 int Bike()
		{
		 	count++;
		 	tnob++;
			amount=amount+30;	
		 	printf("\nYour Bike entry are Sucessfully done.\n");
		}
	
	  int Auto()
		{
		 	count++;
		 	tnoa++;
		 	amount=amount+50;	
		 	printf("Your Auto entry are Sucessfully done.");
		}
	 
	 int Car()
		{
		 	count++;
		 	tnoc++;
		 	amount=amount+60;	
		 	printf("\nYour Car entry are Sucessfully done.\n");
		}
	 
	  int Bus()
		{
		 	count++;
		 	tnobu++;
		 	amount=amount+100;
		 	printf("\nYour Bus entry are Sucessfully done.\n");
		}
	 
	
	  int Other()
		{
		 	count++;
		 	tnoov++;
		 	amount=amount+50;	
		 	printf("\nYour Vehicle entry are Sucessfully done.\n");
		}
		 
	  int Status()
	  {
	  	printf("Total no of Cycles=%d",tnocy);
	  	printf("Total no of Bikes=%d",tnob);
	  	printf("Total no of Autos=%d",tnoa);
	  	printf("Total no of Cares=%d",tnoc);
	  	printf("Total no of Buses=%d",tnobu);
	  	printf("Total no of other vehicles=%d",tnoov);
	  	printf("Total no of vehicles=%d",count);
	  	printf("Total no of amount generated by vehicles=%d",amount);
	  }
	 
	  int Delete()
	  {
	  	printf("\nPress y to delete all data permanently=");
	  	scanf("%c",&a);
	  	
	  	if (a=='Y' || 'y')
	  	{
	  		tnocy=0;
			tnob=0;
			tnoc=0;
			tnoa=0;
			tnobu=0;
			tnoov=0;
			count=0;
			amount=0;
			printf("\nYour data are deleted permanently\n");
		}
		
		else
		{
			printf("\nYour data are safe\n");	
		}
	  }


	  int menu()
	 {
	 	int num=0;
	 	printf("\n Press 1 for Cycle");
	 	printf("\n Press 2 for Bike");
	 	printf("\n Press 3 for Auto");
	 	printf("\n Press 4 for Car");
	 	printf("\n Press 5 for Bus");
	 	printf("\n Press 6 for Other Vehicle");
	 	printf("\n Press 7 for Check Status");
	 	printf("\n Press 8 for Delete all data");
	 	printf("\n Press 9 for exit");
	 	printf("\n\n Please enter your choice=");
	 	scanf("%d",&num);
	 	return(num);
	 }
  
 int main()
   {
       char x ='y';
    while(x=='y')
    {
	   	switch(menu())
 		{
 			case 1:	
			 	Cycle();
			 	break;
			 	
 			case 2:
 				Bike();
			 	break;
			 	
 			case 3:
 				Auto();
			 	break;
			 	
 			case 4:
 				Car();
			 	break;
			 	
			case 5:
				Bus();
			 	break;
			 	
			case 6 :	
				Other();
			 	break;
			 	
			case 7:
				Status();
				break;
			 	
			case 8:
				Delete();
			 	break;
			 	
			case 9:
				
				//exit(0);
				return 0;
			default:	
			 	printf("\nPlease Enter btwn 1-9");
			 	break;
 		}
 		
 		printf("\nEnter N if you want to exit\n");
 	    scanf("%c",&x);
 		scanf("%c",&x);
 	
    }
   }
